[build]
command = "echo 'Static site - no build command needed'"
base = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "echo 'Static site - no build command needed'"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
